{
 "title": "study Monitoring Dashboard Project Separation",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "site_instance",
    "label": "Site",
    "query": {
     "query": "label_values(instance_info,instance)"
    }
   },
   {
    "name": "component",
    "label": "Node Software Component",
    "query": {
     "query": "label_values(component_build_info{job!=\"Pushgateway Metrics\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Status of study Sites",
   "type": "geomap",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "round(time() - instance_info{instance=~\"$site_instance\",job=\"instance_info\"})"
    }
   ]
  },
  {
   "title": "DICOM Modality Distribution",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(modality) (dicom_series_total{job=\"$component\", instance=~\"$site_instance\", modality!=\"total\"})",
     "legendFormat": "{{modality}}"
    }
   ]
  },
  {
   "title": "DICOM Patient Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dicom_patients_total{job=\"$component\", instance=~\"$site_instance\", modality=\"total\", job!=\"Pushgateway Metrics\"}",
     "legendFormat": "Studies"
    }
   ]
  },
  {
   "title": "DICOM Study Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dicom_studies_total{job=\"$component\", instance=~\"$site_instance\", modality=\"total\", job!=\"Pushgateway Metrics\"}",
     "legendFormat": "Studies"
    }
   ]
  },
  {
   "title": "DICOM Series Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "dicom_series_total{job=\"$component\", instance=~\"$site_instance\", modality=\"total\", job!=\"Pushgateway Metrics\"}",
     "legendFormat": "Studies"
    }
   ]
  },
  {
   "title": "Available DICOM Modalities over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 8, "y": 8 },
   "targets": [
    {
     "expr": "sum(dicom_series_total{job=\"$component\", instance=~\"$site_instance\", modality=\"CT\"})",
     "legendFormat": "CT"
    },
    {
     "expr": "sum(dicom_series_total{job=\"$component\",instance=~\"$site_instance\",modality=\"MR\"})",
     "legendFormat": "MR"
    },
    {
     "expr": "sum(dicom_series_total{job=\"$component\",instance=~\"$site_instance\",modality=\"OT\"})",
     "legendFormat": "OT"
    },
    {
     "expr": "sum(dicom_series_total{job=\"$component\",instance=~\"$site_instance\",modality=\"total\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Site's Technical Basic Information",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "component_build_info{instance=~\"$site_instance\",job=~\"$component\"}"
    }
   ]
  },
  {
   "title": "(Average) Component Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(component_uptime_seconds{instance=~\"$site_instance\",job=~\"$component\"})",
     "legendFormat": " $site_instance Uptime"
    }
   ]
  },
  {
   "title": "Jobs Monitoring",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "sum(jobs_success_total{job=\"$component\",instance=~\"$site_instance\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(jobs_failed_total{job=\"$component\",instance=~\"$site_instance\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(jobs_queued_total{job=\"$component\",instance=~\"$site_instance\"})",
     "legendFormat": "Queued"
    }
   ]
  },
  {
   "title": "Component Storage Info: Directory \"/\"",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storage_size_free_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/\"})",
     "legendFormat": "{{mount_point}} Free"
    },
    {
     "expr": "sum(storage_size_total_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/\"} - storage_size_free_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/\"})",
     "legendFormat": "{{mount_point}} Used"
    }
   ]
  },
  {
   "title": "Component Storage Info: Directory \"/home\"",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(storage_size_free_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/home\"})",
     "legendFormat": "{{mount_point}} Free"
    },
    {
     "expr": "sum(storage_size_total_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/home\"} - storage_size_free_bytes{instance=~\"$site_instance\",job=\"$component\",mount_point=\"/home\"})",
     "legendFormat": "{{mount_point}} Used"
    }
   ]
  }
 ]
}